CREATE TABLE LIBRO (
    NRO_LIBRO INT NOT NULL PRIMARY KEY,
    TITULO CHAR(40) NOT NULL,
    AUTOR CHAR(30) NOT NULL,
    TIPO CHAR(2) NOT NULL,
    PRECIO_ORI SMALLMONEY NOT NULL CHECK (PRECIO_ORI > 0),
    PRECIO_ACT SMALLMONEY NOT NULL CHECK (PRECIO_ACT > 0),
    EDICION SMALLINT NOT NULL CHECK (EDICION > 0),
    ESTADO CHAR(1) NOT NULL DEFAULT 'D' CHECK (ESTADO IN ('D', 'N'))
);

CREATE TABLE TIPOLIBRO (
    TIPO CHAR(2) NOT NULL PRIMARY KEY,
    DESCTIPO CHAR(40) NOT NULL
);

CREATE TABLE LECTOR (
    NRO_LECTOR INT NOT NULL PRIMARY KEY,
    NOMBRE CHAR(22) NOT NULL,
    DIRECCION CHAR(30) NOT NULL,
    TRABAJO CHAR(11) NOT NULL CHECK (TRABAJO IN ('EMPLEADO', 'EJECUTIVO', 'VENDEDOR', 'COMERCIANTE')),
    SALARIO SMALLMONEY NOT NULL CHECK (SALARIO > 0),
    ESTADO CHAR(1) NOT NULL DEFAULT 'H' CHECK (ESTADO IN ('H', 'I'))
);

CREATE TABLE COPIAS (
    NRO_LIBRO INT NOT NULL,
    NRO_COPIA SMALLINT NOT NULL,
    ESTADO CHAR(1) NOT NULL CHECK (ESTADO IN ('P', 'D', 'N')),
    PRIMARY KEY (NRO_LIBRO, NRO_COPIA),
    FOREIGN KEY (NRO_LIBRO) REFERENCES LIBRO (NRO_LIBRO)
);

CREATE TABLE PRESTAMO (
    NRO_LECTOR INT NOT NULL,
    NRO_LIBRO INT NOT NULL,
    NRO_COPIA SMALLINT NOT NULL,
    F_PREST DATETIME NOT NULL,
    F_DEVOL DATETIME NULL,
    PRIMARY KEY (NRO_LECTOR, NRO_LIBRO, NRO_COPIA, F_PREST),
    FOREIGN KEY (NRO_LECTOR) REFERENCES LECTOR (NRO_LECTOR),
    FOREIGN KEY (NRO_LIBRO, NRO_COPIA) REFERENCES COPIAS (NRO_LIBRO, NRO_COPIA)
    --La logica de negocio de esas validaciones de estado se cubre con el SP_RegistrarPrestamo.
);

